Set Go server softlinks on local install

diff --git a/utils/setPshellLib b/utils/setPshellLib
--- a/utils/setPshellLib
+++ b/utils/setPshellLib
@@ -33,22 +33,33 @@ then
   echo "Usage: setPshellLib -stub | -full"
   exit 1
 fi
+
+localDir=$(pwd)
+
 if [ -n "$PSHELL_INSTALL" ]
 then
-  LIB_DIR=${PSHELL_INSTALL}/lib
-  PYTHON_DIR=${PSHELL_INSTALL}/python
-  GO_DIR=${PSHELL_INSTALL}/go
-  GO_SRC=$GO_DIR/src/PshellServer
-  GO_SRC_FULL=$GO_DIR/src/PshellServer-full
-  GO_SRC_STUB=$GO_DIR/src/PshellServer-stub
-  GO_PKG=$GO_DIR/pkg/linux_amd64
-  if [ ! -e "${GO_SRC}" ]
-  then
-    mkdir $GO_SRC
-  fi
+  installDir=${PSHELL_INSTALL}
+elif [ ! -e "$localDir/utils/setPshellLib" ]
+then
+  echo "ERROR: This script must be run from top level pshell directory"
+  exit 1
 else
-  PYTHON_DIR=$(pwd)/python
+  installDir=$localDir
 fi
+
+LIB_DIR=$installDir/lib
+PYTHON_DIR=$installDir/python
+GO_DIR=$installDir/go
+GO_SRC=$GO_DIR/src/PshellServer
+GO_SRC_FULL=$GO_DIR/src/PshellServer-full
+GO_SRC_STUB=$GO_DIR/src/PshellServer-stub
+GO_PKG=$GO_DIR/pkg/linux_amd64
+
+if [ ! -e "${GO_SRC}" ]
+then
+  mkdir $GO_SRC
+fi
+
 if [ "$1" == "-stub" ] 
 then
 
@@ -60,6 +71,7 @@ then
   then
     echo "ERROR: Could not find library: '$LIB_DIR/libpshell-server-stub.a'"
   else
+    echo "Setting softlink libpshell-server to libpshell-server-stub"
     rm -f $LIB_DIR/libpshell-server.so
     ln -s $LIB_DIR/libpshell-server-stub.so $LIB_DIR/libpshell-server.so 
     rm -f $LIB_DIR/libpshell-server.a
@@ -71,19 +83,9 @@ then
   then
     echo "ERROR: Could not find module: '$PYTHON_DIR/PshellServer-stub.py'"
   else
+    echo "Setting softlink PshellServer.py PshellServer-stub.py"	
     rm -f $PYTHON_DIR/PshellServer.py
     ln -s $PYTHON_DIR/PshellServer-stub.py $PYTHON_DIR/PshellServer.py 
-  fi
-  
-  # Go library module, static only
-  if [ ! -e "$GO_PKG/PshellServer-stub.a" ]
-  then
-    echo "ERROR: Could not find module: '$GO_PKG/PshellServer-stub.a'"
-  else
-    rm -f $GO_PKG/PshellServer.a
-    ln -s $GO_PKG/PshellServer-stub.a $GO_PKG/PshellServer.a
-    # need to do this to force a re-link when building the demo app
-    touch $GO_PKG/PshellServer.a
   fi
   
   # Go source module
@@ -91,8 +93,21 @@ then
   then
     echo "ERROR: Could not find module: '$GO_SRC_STUB/PshellServer-stub.go'"
   else
+    echo "Setting softlink PshellServer.go PshellServer-stub.go"	
     rm -f $GO_SRC/PshellServer.go
     ln -s $GO_SRC_STUB/PshellServer-stub.go $GO_SRC/PshellServer.go
+  fi
+  
+  # Go library module, static only
+  if [ ! -e "$GO_PKG/PshellServer-stub.a" ]
+  then
+    echo "ERROR: Could not find module: '$GO_PKG/PshellServer-stub.a'"
+  else
+    echo "Setting softlink PshellServer.a PshellServer-stub.a"	
+    rm -f $GO_PKG/PshellServer.a
+    ln -s $GO_PKG/PshellServer-stub.a $GO_PKG/PshellServer.a
+    # need to do this to force a re-link when building the demo app
+    touch $GO_PKG/PshellServer.a
   fi
   
 elif [ "$1" == "-full" ] 
@@ -106,6 +121,7 @@ then
   then
     echo "ERROR: Could not find library: '$LIB_DIR/libpshell-server-full.a'"
   else
+    echo "Setting softlink libpshell-server to libpshell-server-full"
     rm -f $LIB_DIR/libpshell-server.so
     ln -s $LIB_DIR/libpshell-server-full.so $LIB_DIR/libpshell-server.so 
     rm -f $LIB_DIR/libpshell-server.a
@@ -117,19 +133,9 @@ then
   then
     echo "ERROR: Could not find module: '$PYTHON_DIR/PshellServer-full.py'"
   else
+    echo "Setting softlink PshellServer.py PshellServer-full.py"	
     rm -f $PYTHON_DIR/PshellServer.py
     ln -s $PYTHON_DIR/PshellServer-full.py $PYTHON_DIR/PshellServer.py 
-  fi
-  
-  # Go library module, static only
-  if [ ! -e "$GO_PKG/PshellServer-full.a" ]
-  then
-    echo "ERROR: Could not find module: '$GO_PKG/PshellServer-full.a'"
-  else
-    rm -f $GO_PKG/PshellServer.a
-    ln -s $GO_PKG/PshellServer-full.a $GO_PKG/PshellServer.a
-    # need to do this to force a re-link when building the demo app
-    touch $GO_PKG/PshellServer.a
   fi
   
   # Go source module
@@ -137,8 +143,21 @@ then
   then
     echo "ERROR: Could not find module: '$GO_SRC_FULL/PshellServer-full.go'"
   else
+    echo "Setting softlink PshellServer.go PshellServer-full.go"	
     rm -f $GO_SRC/PshellServer.go
     ln -s $GO_SRC_FULL/PshellServer-full.go $GO_SRC/PshellServer.go
+  fi
+  
+  # Go library module, static only
+  if [ ! -e "$GO_PKG/PshellServer-full.a" ]
+  then
+    echo "ERROR: Could not find module: '$GO_PKG/PshellServer-full.a'"
+  else
+    echo "Setting softlink PshellServer.a PshellServer-full.a"	
+    rm -f $GO_PKG/PshellServer.a
+    ln -s $GO_PKG/PshellServer-full.a $GO_PKG/PshellServer.a
+    # need to do this to force a re-link when building the demo app
+    touch $GO_PKG/PshellServer.a
   fi
   
 else
